version: "3.2"
services:
  auth:
    container_name: auth
    build:
      context: './auth'
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - ./auth/:/auth/
    environment:
      JWT_SECRET: ${JWT_SECRET}
  movies:
    container_name: movies
    build:
      context: './movies'
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3001}
        target: 3001
    volumes:
      - ./movies/:/movies/
    environment:
      OMDb_SECRET: ${OMDb_SECRET}
      MONGODB: "mongodb://mongo:27017/docker-node-mongo"
    links:
      - db
      - auth
  db:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  nginx-proxy:
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./proxy
    links:
      - movies
      - auth
    ports:
      - "80:80"
